site_name: Sentinela

theme:
  name: material
  palette:
    primary: brown
    scheme: slate
  logo: assets/sindpol-logo.png
  favicon: assets/sindpol-logo.png

nav:
  - Home: pages/index.md
  - Projeto: pages/projeto.md
  - Guia de Contribuição: pages/guia-contribuicao.md
  - Produto:
      - Visão do Produto: pages/produto/visao-produto.md
      - Canvas MVP: pages/produto/canvas-mvp.md
      - Backlog Inicial: pages/produto/backlog-inicial.md
      - Documento de Arquitetura: pages/produto/documento-arquitetura.md
      - Mapa de rotas: pages/produto/mapa-rotas.md
  - Gestão de Riscos e Recursos:
      - Custo: pages/gestao/custo.md
      - Gestão de risco: pages/gestao/risco.md
      - Gestão de qualidade: pages/gestao/qualidade.md
      - Metodologias: pages/gestao/metodologias.md
  - Protótipos:
      - Alta Fidelidade: pages/prototipos/alta-fidelidade.md
  - Equipe:
      - Quadros de Conhecimento: pages/equipe/quadros-conhecimento.md
      - Dojôs: pages/equipe/dojos.md
      - Quadro de Pareamento: pages/equipe/quadros-pareamento.md
      - Comunicação: pages/equipe/comunicacao.md
      - Agenda de Trabalho: pages/equipe/agenda-trabalho.md
